/* ============================================================
   language.js — Rwanda Cost-of-Living Navigator
   ============================================================
   This file handles the English / Kinyarwanda language toggle.

   How it works:
   - All text on every page has an id like "hero-title"
   - This file stores translations for every id
   - When user clicks the language button, we swap all text
   - The chosen language is saved so it persists across pages
   ============================================================ */


/* ============================================================
   TRANSLATIONS — English and Kinyarwanda
   Add new text here whenever a new page element is added
   ============================================================ */
const translations = {

  en: {
    /* ── Header ── */
    "brand-name"      : "Rwanda Cost-of-Living Navigator",
    "brand-tagline"   : "Powered by official NISR data",
    "lang-label"      : "EN | RW",

    /* ── Hero ── */
    "hero-badge"      : "August 2026 — Latest NISR Data",
    "hero-title"      : "How much is inflation really costing <em>you</em> this month?",
    "hero-subtitle"   : "Rwanda's inflation is at 15.9% — but that number is the national average. Your real inflation depends on what <em>you</em> actually spend money on.",
    "hero-cta"        : "Calculate my personal inflation →",
    "hero-note"       : "Free · No registration · No data stored",

    /* ── Alert bar ── */
    "alert-general"   : "📊 General inflation: <strong>15.9%</strong>",
    "alert-transport" : "🚌 Transport: <strong>+27.5%</strong>",
    "alert-food"      : "🥗 Food: <strong>+16.7%</strong>",
    "alert-housing"   : "🏠 Housing: <strong>+19.9%</strong>",
    "alert-health"    : "💊 Health: <strong>+2.7%</strong>",

    /* ── Tiers ── */
    "tiers-title"     : "Choose your tool",
    "tier1-name"      : "Personal",
    "tier1-desc"      : "Enter your income and expenses — see your real inflation rate, biggest pressures, and practical tips to save money this month.",
    "tier1-link"      : "Open personal tool →",
    "tier2-name"      : "Business",
    "tier2-desc"      : "Track cost pressure across all categories, plan your budget, and see a 3-month forecast for your biggest operating costs.",
    "tier2-link"      : "Open business tool →",
    "tier3-name"      : "Government & Policy",
    "tier3-desc"      : "District-level pressure index across all 30 districts, income group vulnerability scores, and early warning flags for policy intervention.",
    "tier3-link"      : "Open government dashboard →",

    /* ── Data sources ── */
    "data-title"      : "Built on official data",
    "source1-title"   : "NISR CPI",
    "source1-desc"    : "Monthly Consumer Price Index published by the National Institute of Statistics of Rwanda. Updated every month automatically.",
    "source2-title"   : "NISR EICV7",
    "source2-desc"    : "2023-2024 Integrated Household Living Conditions Survey — 15,054 households across all 30 districts of Rwanda.",
    "source3-title"   : "Claude AI",
    "source3-desc"    : "Personalized advice generated by Anthropic's Claude AI — in English and Kinyarwanda. Your data is never stored.",

    /* ── Privacy ── */
    "privacy-text"    : "<strong>Your privacy is protected.</strong> This platform calculates results in real time and never stores your personal spending information. No account required. No data collected.",

    /* ── Footer ── */
    "footer-data"     : "Data: NISR Consumer Price Index · August 2026 · NISR EICV7 2023-2024",
    "footer-disclaimer": "⚠ District pressure scores and forecasts are model estimates — not official NISR figures. All inflation rates are sourced directly from NISR.",

    /* ── Personal page ── */
    "personal-title"  : "Personal Inflation Calculator",
    "income-label"    : "Monthly income (RWF)",
    "food-label"      : "Food and groceries",
    "housing-label"   : "Rent, electricity, water",
    "transport-label" : "Transport",
    "health-label"    : "Health and medicine",
    "education-label" : "Education",
    "clothing-label"  : "Clothing and footwear",
    "communication-label": "Airtime and internet",
    "furnishing-label": "Household items",
    "recreation-label": "Recreation",
    "restaurants-label": "Eating out",
    "misc-label"      : "Personal care and other",
    "calculate-btn"   : "Calculate my inflation rate",
    "your-rate-label" : "Your personal inflation rate",
    "national-label"  : "National average",
    "difference-label": "Difference",
    "biggest-pressure": "Biggest pressure this month",
    "what-changed"    : "What changed this month?",
    "rising-label"    : "🔴 Rising",
    "stable-label"    : "🟡 Stable",
    "falling-label"   : "🟢 Falling",
    "tips-title"      : "Practical tips for your situation",
    "compare-title"   : "How you compare",
    "forecast-title"  : "What to expect next month",
    "ai-btn"          : "🤖 Get personalized AI advice",
    "question-btn"    : "💬 Ask a question",
    "share-btn"       : "📲 Share on WhatsApp",
    "estimate-note"   : "⚠ Model estimate — not a confirmed local price",

    /* ── Business page ── */
    "business-title"  : "Business Cost Intelligence",
    "cost-pressure"   : "Cost pressure by category",
    "forecast-business": "3-month cost forecast",
    "wage-signal"     : "Wage review signal",

    /* ── Government page ── */
    "govt-title"      : "District Pressure Index",
    "district-map"    : "All 30 districts — cost-of-living pressure",
    "vulnerability"   : "Income group vulnerability",
    "early-warnings"  : "Early warning flags",
    "national-summary": "National summary",
  },

  rw: {
    /* ── Header ── */
    "brand-name"      : "Igipimo cy'ihindagurika ry'Ibiciro mu Rwanda",
    "brand-tagline"   : "Hifashishijwe amakuru ya NISR",
    "lang-label"      : "RW | EN",

    /* ── Hero ── */
    "hero-badge"      : "Kanama 2026 — Amakuru mashya ya NISR",
    "hero-title"      : "Inflation iramarira <em>wowe</em> angahe uno mwezi?",
    "hero-subtitle"   : "Inflation mu Rwanda iri ku 15.9% — ariko uwo mubare ni uburinganire bw'igihugu. Inflation yawe nyayo ishingira ku kintu <em>wewe</em> usanga ukoresha amafaranga.",
    "hero-cta"        : "Barura inflation yanjye →",
    "hero-note"       : "Ubuntu · Nta kwiyandikisha · Nta makuru abikwa",

    /* ── Alert bar ── */
    "alert-general"   : "📊 Inflation
