/* ============================================================
   language.js — Rwanda Cost-of-Living Navigator
   ============================================================
   This file handles the English / Kinyarwanda language toggle.

   How it works:
   - All text on every page has an id like "hero-title"
   - This file stores translations for every id
   - When user clicks the language button, we swap all text
   - The chosen language is saved so it persists across pages
   ============================================================ */


/* ============================================================
   TRANSLATIONS — English and Kinyarwanda
   Add new text here whenever a new page element is added
   ============================================================ */
const translations = {

  en: {
    /* ── Header ── */
    "brand-name"      : "Rwanda Cost-of-Living Navigator",
    "brand-tagline"   : "Powered by official NISR data",
    "lang-label"      : "EN | RW",

    /* ── Hero ── */
    "hero-badge"      : "August 2026, Latest NISR Data",
    "hero-title"      : "How much is inflation really costing <em>you</em> this month?",
    "hero-subtitle"   : "Rwanda's inflation is at 15.9%, but that number is the national average. Your real inflation depends on what <em>you</em> actually spend money on.",
    "hero-cta"        : "Calculate my personal inflation →",
    "hero-note"       : "Free · No registration · No data stored",

    /* ── Alert bar ── */
    "alert-general"   : "📊 General inflation: <strong>15.9%</strong>",
    "alert-transport" : "🚌 Transport: <strong>+27.5%</strong>",
    "alert-food"      : "🥗 Food: <strong>+16.7%</strong>",
    "alert-housing"   : "🏠 Housing: <strong>+19.9%</strong>",
    "alert-health"    : "💊 Health: <strong>+2.7%</strong>",

    /* ── Tiers ── */
    "tiers-title"     : "Choose your tool",
    "tier1-name"      : "Personal",
    "tier1-desc"      : "Enter your income and expenses and see your real inflation rate, biggest pressures, and practical tips to save money this month.",
    "tier1-link"      : "Open personal tool →",
    "tier2-name"      : "Business",
    "tier2-desc"      : "Track cost pressure across all categories, plan your budget, and see a 3-month forecast for your biggest operating costs.",
    "tier2-link"      : "Open business tool →",
    "tier3-name"      : "Government & Policy",
    "tier3-desc"      : "District-level pressure index across all 30 districts, income group vulnerability scores, and early warning flags for policy intervention.",
    "tier3-link"      : "Open government dashboard →",

    /* ── Data sources ── */
    "data-title"      : "Built on official data",
    "source1-title"   : "NISR CPI",
    "source1-desc"    : "Monthly Consumer Price Index published by the National Institute of Statistics of Rwanda. Updated every month automatically.",
    "source2-title"   : "NISR EICV7",
    "source2-desc"    : "2023-2024 Integrated Household Living Conditions Survey — 15,054 households across all 30 districts of Rwanda.",
    "source3-title"   : "Gemini AI",
    "source3-desc"    : "Personalized advice generated by Google Gemini AI — in English and Kinyarwanda. Your data is never stored",

    /* ── Privacy ── */
    "privacy-text"    : "<strong>Your privacy is protected.</strong> This platform calculates results in real time and never stores your personal spending information. No account required. No data collected.",

    /* ── Footer ── */
    "footer-data"     : "Data: NISR Consumer Price Index · August 2026 · NISR EICV7 2023-2024",
    "footer-disclaimer": "⚠ District pressure scores and forecasts are model estimates — not official NISR figures. All inflation rates are sourced directly from NISR.",

    /* ── Personal page ── */
    "personal-title"  : "Personal Inflation Calculator",
    "income-label"    : "Monthly income (RWF)",
    "food-label"      : "Food and groceries",
    "housing-label"   : "Rent, electricity, water",
    "transport-label" : "Transport",
    "health-label"    : "Health and medicine",
    "education-label" : "Education",
    "clothing-label"  : "Clothing and footwear",
    "communication-label": "Airtime and internet",
    "furnishing-label": "Household items",
    "recreation-label": "Recreation",
    "restaurants-label": "Eating out",
    "misc-label"      : "Personal care and other",
    "calculate-btn"   : "Calculate my inflation rate",
    "your-rate-label" : "Your personal inflation rate",
    "national-label"  : "National average",
    "difference-label": "Difference",
    "biggest-pressure": "Biggest pressure this month",
    "what-changed"    : "What changed this month?",
    "rising-label"    : "🔴 Rising",
    "stable-label"    : "🟡 Stable",
    "falling-label"   : "🟢 Falling",
    "tips-title"      : "Practical tips for your situation",
    "compare-title"   : "How you compare",
    "forecast-title"  : "What to expect next month",
    "ai-btn"          : "🤖 Get personalized Gemini AI advice",
    "question-btn"    : "💬 Ask a question",
    "share-btn"       : "📲 Share on WhatsApp",
    "estimate-note"   : "⚠ Model estimate — not a confirmed local price",

    /* ── Business page ── */
    "business-title"  : "Business Cost Intelligence",
    "cost-pressure"   : "Cost pressure by category",
    "forecast-business": "3-month cost forecast",
    "wage-signal"     : "Wage review signal",

    /* ── Government page ── */
    "govt-title"      : "District Pressure Index",
    "district-map"    : "All 30 districts — cost-of-living pressure",
    "vulnerability"   : "Income group vulnerability",
    "early-warnings"  : "Early warning flags",
    "national-summary": "National summary",
  },
   
  rw: {
    /* ── Header ── */
    "brand-name"      : "Rwanda Cost-of-Living Navigator",
    "brand-tagline"   : "Hashingiwe kumakuru yemewe ya NISR",
    "lang-label"      : "RW | EN",

  /* ── Hero ── */
  "hero-badge"      : "Kanama 2026 — Amakuru mashya ya NISR",
  "hero-title"      : "Muri uku kwezi, izamuka ry’ibiciro riragutwara angahe <em>wowe</em>?",
  "hero-subtitle"   : "Izamuka rusange ry’ibiciro mu Rwanda riri kuri 15.9% — ariko uwo mubare ni impuzandengo y’igihugu. Izamuka ry’ibiciro rikureba <em>wowe</em> rishingira ku byo ukoresha amafaranga yawe.",
  "hero-cta"        : "Bara izamuka ry’ibiciro rikureba →",
  "hero-note"       : "Ku buntu · Nta kwiyandikisha · Nta makuru abikwa",

  /* ── Alert bar ── */
  "alert-general"   : "📊 Izamuka rusange ry’ibiciro: <strong>15.9%</strong>",
  "alert-transport" : "🚌 Ubwikorezi: <strong>+27.5%</strong>",
  "alert-food"      : "🥗 Ibiribwa: <strong>+16.7%</strong>",
  "alert-housing"   : "🏠 Inzu, amazi n’amashanyarazi: <strong>+19.9%</strong>",
  "alert-health"    : "💊 Ubuzima: <strong>+2.7%</strong>",

  /* ── Tiers ── */
  "tiers-title"     : "Hitamo igikoresho ushaka gukoresha",
  "tier1-name"      : "Umuntu ku giti cye",
  "tier1-desc"      : "Shyiramo amafaranga winjiza n’ayo ukoresha — reba izamuka ry’ibiciro rikureba, ibyiciro bigutwara amafaranga menshi, n’inama zagufasha kuzigama muri uku kwezi.",
  "tier1-link"      : "Fungura igikoresho cy’umuntu ku giti cye →",

  "tier2-name"      : "Ubucuruzi",
  "tier2-desc"      : "Kurikirana uko ibiciro bihinduka mu byiciro bitandukanye, tegura ingengo y’imari yawe, kandi urebe uko ibiciro by’ibikorwa by’ubucuruzi bishobora kuzaba mu mezi 3 ari imbere.",
  "tier2-link"      : "Fungura igikoresho cy’ubucuruzi →",

  "tier3-name"      : "Leta n’Abafata Ibyemezo",
  "tier3-desc"      : "Reba igipimo cy’igitutu cy’ibiciro mu turere twose 30, intege nke z’amatsinda y’abaturage hakurikijwe amafaranga binjiza, n’ibimenyetso by’ibibazo bishobora gusaba igikorwa cya Leta.",
  "tier3-link"      : "Fungura dashboard ya Leta →",

  /* ── Data sources ── */
  "data-title"      : "Yubakiye ku makuru yemewe",
  "source1-title"   : "NISR CPI",
  "source1-desc"    : "Igipimo cy’Ibiciro ku Muguzi (Consumer Price Index) gitangazwa buri kwezi n’Ikigo cy’Igihugu cy’Ibarurishamibare, NISR. Amakuru avugururwa buri kwezi.",
  
  "source2-title"   : "NISR EICV7",
  "source2-desc"    : "Ubushakashatsi ku mibereho y’ingo 2023–2024 — bukorewe ku ngo 15,054 zo mu turere twose 30 tw’u Rwanda.",

  "source3-title"   : "Gemini AI",
  "source3-desc"    : "Inama zihariye zitangwa na Google Gemini AI — mu Cyongereza no mu Kinyarwanda. Amakuru yawe ntabwo abikwa.",

  /* ── Privacy ── */
  "privacy-text"    : "<strong>Amakuru yawe bwite ararinzwe.</strong> Uru rubuga rubara ibisubizo ako kanya kandi ntirubika amakuru ajyanye n’uko ukoresha amafaranga yawe. Nta konti isabwa kandi nta makuru yawe abikwa.",

  /* ── Footer ── */
  "footer-data"     : "Amakuru: NISR Consumer Price Index · Kanama 2026 · NISR EICV7 2023–2024",
  "footer-disclaimer": "⚠ Ibipimo by’igitutu cy’ibiciro mu turere n’ibiteganyijwe ni imibare yagereranyijwe hakoreshejwe model — si imibare yemewe yatangajwe na NISR. Ibipimo byose by’izamuka ry’ibiciro bikomoka kuri NISR.",

  /* ── Personal page ── */
  "personal-title"  : "Igikoresho cyo Kubara Izamuka ry’Ibiciro Rikureba",
  "income-label"    : "Amafaranga winjiza buri kwezi (RWF)",
  "food-label"      : "Ibiribwa n’ibyo kurya byo mu rugo",
  "housing-label"   : "Ubukode, amashanyarazi n’amazi",
  "transport-label" : "Ubwikorezi",
  "health-label"    : "Ubuzima n’imiti",
  "education-label" : "Uburezi",
  "clothing-label"  : "Imyambaro n’inkweto",
  "communication-label": "Amayinite na internet",
  "furnishing-label": "Ibikoresho byo mu rugo",
  "recreation-label": "Imyidagaduro",
  "restaurants-label": "Kurira muri resitora cyangwa ahandi",
  "misc-label"      : "Isuku n’ubwiza bw’umuntu n’ibindi",
  "calculate-btn"   : "Bara izamuka ry’ibiciro rikureba",
  "your-rate-label" : "Izamuka ry’ibiciro rikureba",
  "national-label"  : "Impuzandengo y’igihugu",
  "difference-label": "Itandukaniro",
  "biggest-pressure": "Icyiciro kiguhenda cyane muri uku kwezi",
  "what-changed"    : "Ni iki cyahindutse muri uku kwezi?",
  "rising-label"    : "🔴 Birazamuka",
  "stable-label"   : "🟡 Ntibyahindutse cyane",
  "falling-label"   : "🟢 Biragabanuka",
  "tips-title"      : "Inama zijyanye n’imikoreshereze yawe",
  "compare-title"   : "Ugereranyije n’abandi",
  "forecast-title"  : "Ibyitezwe mu kwezi gutaha",
  "ai-btn"          : "🤖 Shaka inama zihariye za AI",
  "question-btn"    : "💬 Baza ikibazo",
  "share-btn"       : "📲 Sangiza kuri WhatsApp",
  "estimate-note"   : "⚠ Iyi ni imibare yagereranyijwe na model — ntabwo ari igiciro cyemejwe cyo ku isoko",

  /* ── Business page ── */
  "business-title"  : "Amakuru y’Ibiciro by’Ubucuruzi",
  "cost-pressure"   : "Igitutu cy’ibiciro hakurikijwe ibyiciro",
  "forecast-business": "Iteganyabiciro ry’amezi 3 ari imbere",
  "wage-signal"     : "Ikimenyetso gifasha mu gusuzuma umushahara",

  /* ── Government page ── */
  "govt-title"      : "Igipimo cy’Igitutu cy’Ibiciro mu Turere",
  "district-map"    : "Uturere twose 30 — Igitutu cy’ibiciro by’imibereho",
  "vulnerability"   : "Intege nke z’amatsinda hakurikijwe amafaranga yinjiza",
  "early-warnings"  : "Ibimenyetso by’ibibazo bishobora kugaragara mbere",
  "national-summary": "Incamake y’igihugu",
},
